### ISSUE TITLE
Nothing but the source dropdown is showing

### ISSUE THREAD

**Issue by rcpilotp51** [custom-cards/roku-card#13]
I was able to get everything installed without error, however the icons are showing for the remote card. SS attached
![Screen Shot 2019-06-17 at 2 42 10 PM](https://user-images.githubusercontent.com/15835122/59628223-1d615b00-910e-11e9-9bcb-4c94a1359af8.png)

Any suggestions on how to fix this?

**Comment by thizzle** [comment]
I experienced the same thing.

I was able to resolve this by replacing instances of `paper-icon-button` with `ha-icon` in the `roku-card.js` source. I'm not really sure why this worked. 🤷‍♂

**Comment by iantrich** [comment]
Thanks for the work-around. Going to do a full rewrite soon on this and should avoid silly dependency things like this.
