### ISSUE TITLE
[0.97] Bug: Card won't display when Roku media_player's state is "off"

### ISSUE THREAD

**Issue by manutenfruits** [custom-cards/roku-card#17]
I was testing 0.97 and noticed that my card won't show up (I see an empty shadow root element) when the media_player is off. It's off because it's a Roku TV.

I tried debugging the code but wasn't initially obvious why, as HTML gets returned from the .render() function.

**Comment by iantrich** [comment]
errors in console?

**Comment by manutenfruits** [comment]
Hey sorry, I hit the send button too early, but yes! I found it, it seems like it's a bug from the HA implementation, because it returns no source_list on the state attribute's. I'll follow up there!

![image](https://user-images.githubusercontent.com/2961735/62377203-59ab1800-b510-11e9-8894-f2c31be5dd68.png)

**Comment by iantrich** [comment]
Going to keep this open and plan to at least add a check for the source list before trying to display it

**Comment by iantrich** [comment]
I'm at work at the moment so can't test this: https://gist.github.com/iantrich/f88f0c644e826e402707cf2e5d7e1170

**Comment by iantrich** [comment]
Fixed in https://github.com/custom-cards/roku-card/releases/tag/1.0.0
