### ISSUE TITLE
input source always sent

### ISSUE THREAD

**Issue by alex-phillips** [custom-cards/roku-card#18]
Every time the page reloads, it sends the input source command which causes apps to restart if you're in the middle of watching something. Is there a way to just disable that input source drop-down / function completely?

**Comment by iantrich** [comment]
I'm surprised I never noticed that. I'll look into that. You cannot current remove it without editing the file itself. My very first iteration had buttons for your 4 favorite apps instead of the full list. I liked that a lot more and might go back to that. This card needs an overhaul

**Comment by alex-phillips** [comment]
Yeah - I don't think it's an issue by default until you actually select a source from that dropdown. Then the source is set to a value. In the card's code, it launches the source if the dropdown is not `""`, so then it's "forever" set to launch that source (or whatever source you set to). Maybe a way to reset or disable it?

**Comment by iantrich** [comment]
Yeah. Should only set on a change, obviously. I'll take a look. Thanks n

**Comment by fbanville** [comment]
This is strange. I only started to experience this problem when I upgraded to hassio 0.97. I fixed temporarly the issue by disabling the input source changing javascript function. I commented line 233 of roku-card.js and added a dummy if statement. This is my most useful lovelace card. Thank you so much for it!
```
//    if (e.currentTarget.value != "") {
    if (false) {
```

**Comment by alex-phillips** [comment]
I did the same thing but it doesn't look like it's getting sent down to the browser. I restarted home assistant and cleared my cash but it's still sending down the original file. Any suggestions?

**Comment by fbanville** [comment]
Well, I did struggle a bit to get the change to my  clients but it all works in the end. Here is what I did:
1) I changed the roku-card.js file
2) I restarted hassio
3) For my chrome based clients I refreshed the browswer using CTRL-F5
4) For the android devices using a PWA (web app saved to the home screen) I had to uninstall the app (not just remove it from the home page but really uninstall it). I also cleared the cache in chrome. Then I could resave it to the home page and it worked.
5) For iOS devices I also had to remove the apps and clear the safari cache. THe I could resave the app using safari.

I have a feeling this complexity is more likely due to my ignorance than anything else, There must be a simpler way to do this! 

I have the custom card defined in my ui-lovelace.yaml as:
```
resources:
  - url: /local/roku-card.js?v=0
    type: module
```
and I think one can control the refresh using the ```?v=0``` but I do not know how it works.

**Comment by fbanville** [comment]
Thank you @mheppner

**Comment by iantrich** [comment]
So as part of the rewrite I was planning on removing the source_list dropdown and putting 4 select buttons instead. It's actually the design I had initially, as it is more like the actual Roku remotes. Thoughts? Here's the old design and I think I'll do something similar again:

![image](https://user-images.githubusercontent.com/1287159/63177702-1a032680-c00e-11e9-8078-7567debaf8fc.png)

**Comment by alex-phillips** [comment]
I love it! As long as it can be configurable as to which buttons are displayed.

**Comment by iantrich** [comment]
@alex-phillips  absolutely :)

**Comment by iantrich** [comment]
I think I'll be adding tap/hold/repeat/double click actions as well to ALL buttons

**Comment by iantrich** [comment]
the repeat one will be really nice for fast forwarding

**Comment by iantrich** [comment]
maybe I'll do style per button as well...no promise on that

**Comment by fbanville** [comment]
I also love the idea of the 4 select buttons. I only use one or two roku services anyway. However, I can see other things to do with them. Style per button? I do not see any use case for me, but that's only me ;-) I do see some use cases for the tap/hold/repeat/double click actions. I do not see the power and sound controls on your new/old design. To me, this is a key thing I love about the current design.  Keep up the great work!

**Comment by iantrich** [comment]
@fbanville tv controls will still be there

**Comment by fbanville** [comment]
@iantrich Ouf, merci!

**Comment by marcmontecalvo** [comment]
Personally I like the dropdown better than the buttons.  It would be nice to be able to trim down the list in the dropdown though.  Maybe have an option for using the dropdown or using the buttons?  And if you choose the dropdown option have an option for which things you want to show or hide?

**Comment by iantrich** [comment]
Fixed in https://github.com/custom-cards/roku-card/releases/tag/1.0.0
