### ISSUE TITLE
Roku Card Editor

### ISSUE THREAD

**Issue by HouseAutomations** [custom-cards/roku-card#25]
Can't seem to locate this file to add to my www.
because of this when I add the custom card to my UI i get this : 
TypeError: Failed to fetch dynamically imported module: https://secret.duckdns.org:8123/local/roku-card-editor.js

**Comment by iantrich** [comment]
Readme should be updated, there is no longer an editor included

**Comment by HouseAutomations** [comment]
When was this updated? I'm new to HA and Github

**Comment by iantrich** [comment]
https://github.com/custom-cards/roku-card/releases/tag/1.0.0

I've updated the readme file to not reference the editor anymore. Just don't include the resource line about importing the editor and you'll be fine.

**Comment by iantrich** [comment]
Make sure you're downloading from the dist folder

**Comment by HouseAutomations** [comment]
That did it, thanks!
