### ISSUE TITLE
core-2021.11.0b0 seems to have broken the roku card

### ISSUE THREAD

**Issue by arlynxyu** [custom-cards/roku-card#67]
![roku card](https://user-images.githubusercontent.com/69994250/139246291-87af8744-5c3b-4777-b622-c1bbf4f2907d.png)
hey there i just updated to core-2021.11.0b0 yesterday and it seems to have busted the roku card for some reason?  none of the default icons show up all though when hover over them there is a shadow

**Comment by DTTerastar** [comment]
Still broke in 2021.11.0b4

**Comment by firestrife23** [comment]
The issue persist with 2021.11.0 release

**Comment by benblb** [comment]
2021.11.0, same here. PS awesome card and I use it all the time!

**Comment by OverZealous** [comment]
If it helps any, the same [issue happened to the mini-media-player card](https://github.com/kalkih/mini-media-player/issues/555).

[Their fix looks pretty simple, which you can see in this PR.](https://github.com/kalkih/mini-media-player/pull/556)

**Comment by iantrich** [comment]
Lost my dev environment and couldn't dedicate much time to fixing that and properly testing a fix. Here's a pre-release to try: https://github.com/iantrich/roku-card/releases/tag/1.2.3

**Comment by arlynxyu** [comment]
fix does not fix it for me, neither does the update pushed to hacs

**Comment by JBassett** [comment]
> Lost my dev environment and couldn't dedicate much time to fixing that and properly testing a fix. Here's a pre-release to try: https://github.com/iantrich/roku-card/releases/tag/1.2.3

This fixed it for me, thanks.

**Comment by iantrich** [comment]
> fix does not fix it for me, neither does the update pushed to hacs

Did you clear your browser cache?

**Comment by arlynxyu** [comment]
no, i'll give that a shot, apologies

**Comment by firestrife23** [comment]
> Lost my dev environment and couldn't dedicate much time to fixing that and properly testing a fix. Here's a pre-release to try: https://github.com/iantrich/roku-card/releases/tag/1.2.3

It's working!
